[versions]
# Plugins
agp = "9.0.0"
kotlin = "2.3.0"
gms = "4.4.4"

# Dependencies
coreKtx = "1.17.0"
appcompat = "1.7.1"
activity = "1.12.2"
material = "1.13.0"
design = "28.0.0"
constraintlayout = "2.2.1"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"

# Third-party Dependencies
retrofit = "3.0.0"
okhttp3 = "5.3.2"
converterGson = "3.0.0"
loggingInterceptor = "5.3.2"
flexbox = "3.0.0"
lottie = "6.7.1"
glide = "5.0.5"
swipeRefreshLayout = "1.2.0"
circleIndicator = "2.1.6"
appxupdater = "v2.0.20"
pusherJavaClient = "2.4.4"
balloon = "1.7.3"
shimmer = "0.5.0"

firebaseBom = "34.8.0"
firebaseMessaging = "25.0.1"
playServicesMaps = "20.0.0"
playServicesLocation = "21.3.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
design = { module = "com.android.support:design", version.ref = "design" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }

# Third-party Libraries
okhttp3 = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp3" }
okhttp3-sse = { group = "com.squareup.okhttp3", name = "okhttp-sse", version.ref = "okhttp3" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
converter-gson = { group = "com.squareup.retrofit2", name = "converter-gson", version.ref = "converterGson" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glide-compiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
glide-okhttp-integration = { group = "com.github.bumptech.glide", name = "okhttp3-integration", version.ref = "glide" }
swipeRefreshLayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "swipeRefreshLayout" }
circleIndicator = { group = "me.relex", name = "circleIndicator", version.ref = "circleIndicator" }
appxupdater = { module = "com.github.TutorialsAndroid:AppXUpdater", version.ref = "appxupdater" }
pusher-java-client = { module = "com.pusher:pusher-java-client", version.ref = "pusherJavaClient" }
balloon = { module = "com.github.skydoves:balloon", version.ref = "balloon" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }

firebase-bom = { module = "com.google.firebase:firebase-bom", name = "firebase-bom", version.ref = "firebaseBom" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics", name = "firebase-analytics" }
firebase-messaging = { module = "com.google.firebase:firebase-messaging", version.ref = "firebaseMessaging" }
play-services-maps = { group = "com.google.android.gms", name = "play-services-maps", version.ref = "playServicesMaps" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "playServicesLocation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt" }
gms-services = { id = "com.google.gms.google-services", version.ref = "gms" }
